import os
from dataclasses import dataclass
from typing import Optional

import psycopg
from psycopg.rows import dict_row


@dataclass(frozen=True)
class Video:
    id: int
    owner_user_id: int
    file_id: str


class DB:
    def __init__(self, database_url: Optional[str] = None):
        self.database_url = database_url or os.getenv("DATABASE_URL")
        if not self.database_url:
            raise RuntimeError("Set DATABASE_URL environment variable")
        self.conn = psycopg.connect(self.database_url, row_factory=dict_row)
        self._init()

    def close(self) -> None:
        self.conn.close()

    def _init(self) -> None:
        cur = self.conn.cursor()

        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS users (
              user_id BIGINT PRIMARY KEY,
              username TEXT,
              has_video BOOLEAN NOT NULL DEFAULT FALSE,
              active_chat_user_id BIGINT,
              partner_check_attempted BOOLEAN NOT NULL DEFAULT FALSE,
              age INTEGER,
              gender TEXT,
              looking_for TEXT,
              about TEXT,
              profile_complete BOOLEAN NOT NULL DEFAULT FALSE,
              banned BOOLEAN NOT NULL DEFAULT FALSE,
              banned_notified BOOLEAN NOT NULL DEFAULT FALSE,
              video_hidden BOOLEAN NOT NULL DEFAULT FALSE,
              created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
            );
            """
        )

        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS videos (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              owner_user_id BIGINT NOT NULL UNIQUE,
              file_id TEXT NOT NULL,
              created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
              FOREIGN KEY (owner_user_id) REFERENCES users(user_id) ON DELETE CASCADE
            );
            """
        )

        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS views (
              viewer_user_id BIGINT NOT NULL,
              video_id BIGINT NOT NULL,
              viewed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
              PRIMARY KEY (viewer_user_id, video_id),
              FOREIGN KEY (viewer_user_id) REFERENCES users(user_id) ON DELETE CASCADE,
              FOREIGN KEY (video_id) REFERENCES videos(id) ON DELETE CASCADE
            );
            """
        )

        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS complaints (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              reporter_user_id BIGINT NOT NULL,
              video_id BIGINT NOT NULL,
              created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
              FOREIGN KEY (reporter_user_id) REFERENCES users(user_id) ON DELETE CASCADE,
              FOREIGN KEY (video_id) REFERENCES videos(id) ON DELETE CASCADE
            );
            """
        )

        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS ratings (
              rater_user_id BIGINT NOT NULL,
              video_id BIGINT NOT NULL,
              value INTEGER NOT NULL, -- 1=like, -1=dislike
              created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
              PRIMARY KEY (rater_user_id, video_id),
              FOREIGN KEY (rater_user_id) REFERENCES users(user_id) ON DELETE CASCADE,
              FOREIGN KEY (video_id) REFERENCES videos(id) ON DELETE CASCADE
            );
            """
        )

        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS partner_verifications (
              user_id BIGINT PRIMARY KEY,
              verified_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
              FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
            );
            """
        )

        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS chat_topics (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              user1_id BIGINT NOT NULL,
              user2_id BIGINT NOT NULL,
              group_chat_id BIGINT NOT NULL,
              topic_id BIGINT NOT NULL,
              created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
              active BOOLEAN NOT NULL DEFAULT TRUE
            );
            """
        )

        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS settings (
              key TEXT PRIMARY KEY,
              value TEXT NOT NULL
            );
            """
        )

        self.conn.commit()


    def ensure_user(self, user_id: int, username: Optional[str] = None) -> None:
        cur = self.conn.cursor()
        if username is None:
            cur.execute(
                "INSERT INTO users(user_id) VALUES (%s) ON CONFLICT (user_id) DO NOTHING;",
                (user_id,),
            )
        else:
            cur.execute(
                """
                INSERT INTO users(user_id, username)
                VALUES (%s, %s)
                ON CONFLICT (user_id) DO UPDATE SET username=EXCLUDED.username;
                """,
                (user_id, username),
            )
        self.conn.commit()

    def get_user_state(self, user_id: int, username: Optional[str] = None) -> dict:
        cur = self.conn.cursor()
        cur.execute(
            """
            INSERT INTO users(user_id, username)
            VALUES (%s, %s)
            ON CONFLICT (user_id) DO UPDATE SET username=EXCLUDED.username
            RETURNING user_id, username, banned, banned_notified,
                      profile_complete, has_video, active_chat_user_id;
            """,
            (user_id, username),
        )
        row = cur.fetchone()
        self.conn.commit()
        return dict(row)

    def get_username(self, user_id: int) -> Optional[str]:
        self.ensure_user(user_id)
        cur = self.conn.cursor()
        cur.execute("SELECT username FROM users WHERE user_id=%s;", (user_id,))
        row = cur.fetchone()
        if not row:
            return None
        return row["username"]

    def get_active_chat_user(self, user_id: int) -> Optional[int]:
        cur = self.conn.cursor()
        cur.execute("SELECT active_chat_user_id FROM users WHERE user_id=%s;", (user_id,))
        row = cur.fetchone()
        if not row or row["active_chat_user_id"] is None:
            return None
        return int(row["active_chat_user_id"])

    def start_chat(self, user_id: int, partner_user_id: int) -> None:
        self.ensure_user(user_id)
        self.ensure_user(partner_user_id)
        cur = self.conn.cursor()
        cur.execute("UPDATE users SET active_chat_user_id=%s WHERE user_id=%s;", (partner_user_id, user_id))
        cur.execute("UPDATE users SET active_chat_user_id=%s WHERE user_id=%s;", (user_id, partner_user_id))
        self.conn.commit()

    def set_forum_chat_id(self, chat_id: int) -> None:
        cur = self.conn.cursor()
        cur.execute(
            "INSERT INTO settings(key, value) VALUES('forum_chat_id', %s) "
            "ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value;",
            (str(chat_id),),
        )
        self.conn.commit()

    def get_forum_chat_id(self) -> Optional[int]:
        cur = self.conn.cursor()
        cur.execute("SELECT value FROM settings WHERE key='forum_chat_id' LIMIT 1;")
        row = cur.fetchone()
        if not row:
            return None
        try:
            return int(row["value"])
        except (TypeError, ValueError):
            return None

    def create_chat_topic(self, user1_id: int, user2_id: int, group_chat_id: int, topic_id: int) -> None:
        cur = self.conn.cursor()
        cur.execute(
            """
            INSERT INTO chat_topics(user1_id, user2_id, group_chat_id, topic_id)
            VALUES (%s, %s, %s, %s);
            """,
            (user1_id, user2_id, group_chat_id, topic_id),
        )
        self.conn.commit()

    def get_active_chat_topic(self, user_id: int) -> Optional[dict]:
        cur = self.conn.cursor()
        cur.execute(
            """
            SELECT group_chat_id, topic_id
            FROM chat_topics
            WHERE active=TRUE AND (user1_id=%s OR user2_id=%s)
            ORDER BY id DESC LIMIT 1;
            """,
            (user_id, user_id),
        )
        row = cur.fetchone()
        if not row:
            return None
        return {"group_chat_id": int(row["group_chat_id"]), "topic_id": int(row["topic_id"])}

    def close_chat_topic(self, user_id: int) -> Optional[dict]:
        cur = self.conn.cursor()
        cur.execute(
            """
            SELECT group_chat_id, topic_id
            FROM chat_topics
            WHERE active=TRUE AND (user1_id=%s OR user2_id=%s)
            ORDER BY id DESC LIMIT 1;
            """,
            (user_id, user_id),
        )
        row = cur.fetchone()
        if not row:
            return None
        cur.execute(
            """
            UPDATE chat_topics SET active=FALSE
            WHERE active=TRUE AND (user1_id=%s OR user2_id=%s);
            """,
            (user_id, user_id),
        )
        self.conn.commit()
        return {"group_chat_id": int(row["group_chat_id"]), "topic_id": int(row["topic_id"])}

    def end_chat(self, user_id: int) -> Optional[int]:
        self.ensure_user(user_id)
        partner_user_id = self.get_active_chat_user(user_id)
        cur = self.conn.cursor()
        cur.execute("UPDATE users SET active_chat_user_id=NULL WHERE user_id=%s;", (user_id,))
        if partner_user_id is not None:
            cur.execute(
                "UPDATE users SET active_chat_user_id=NULL WHERE user_id=%s AND active_chat_user_id=%s;",
                (partner_user_id, user_id),
            )
        self.conn.commit()
        return partner_user_id

    def get_search_state(self, user_id: int) -> dict:
        cur = self.conn.cursor()
        cur.execute(
            """
            SELECT banned, active_chat_user_id, profile_complete, has_video
            FROM users
            WHERE user_id=%s;
            """,
            (user_id,),
        )
        row = cur.fetchone()
        if not row:
            return {
                "banned": False,
                "active_chat_user_id": None,
                "profile_complete": False,
                "has_video": False,
            }
        return {
            "banned": bool(row["banned"]),
            "active_chat_user_id": row["active_chat_user_id"],
            "profile_complete": bool(row["profile_complete"]),
            "has_video": bool(row["has_video"]),
        }

    def user_has_video(self, user_id: int) -> bool:
        cur = self.conn.cursor()
        cur.execute("SELECT has_video FROM users WHERE user_id=%s;", (user_id,))
        row = cur.fetchone()
        return bool(row and row["has_video"])

    def profile_complete(self, user_id: int) -> bool:
        cur = self.conn.cursor()
        cur.execute("SELECT profile_complete FROM users WHERE user_id=%s;", (user_id,))
        row = cur.fetchone()
        return bool(row and row["profile_complete"])

    def is_banned(self, user_id: int) -> bool:
        cur = self.conn.cursor()
        cur.execute("SELECT banned FROM users WHERE user_id=%s;", (user_id,))
        row = cur.fetchone()
        return bool(row and row["banned"])

    def ban_user(self, user_id: int) -> None:
        self.ensure_user(user_id)
        cur = self.conn.cursor()
        cur.execute("UPDATE users SET banned=TRUE, banned_notified=FALSE WHERE user_id=%s;", (user_id,))
        self.conn.commit()

    def banned_notified(self, user_id: int) -> bool:
        self.ensure_user(user_id)
        cur = self.conn.cursor()
        cur.execute("SELECT banned_notified FROM users WHERE user_id=%s;", (user_id,))
        row = cur.fetchone()
        return bool(row and row["banned_notified"])

    def set_banned_notified(self, user_id: int) -> None:
        self.ensure_user(user_id)
        cur = self.conn.cursor()
        cur.execute("UPDATE users SET banned_notified=TRUE WHERE user_id=%s;", (user_id,))
        self.conn.commit()

    def set_profile(
        self,
        user_id: int,
        age: int,
        gender: str,
        looking_for: str,
        about: str,
    ) -> None:
        self.ensure_user(user_id)
        cur = self.conn.cursor()
        cur.execute(
            """
            UPDATE users
            SET age=%s,
                gender=%s,
                looking_for=%s,
                about=%s,
                profile_complete=TRUE
            WHERE user_id=%s;
            """,
            (age, gender, looking_for, about, user_id),
        )
        self.conn.commit()

    def get_profile(self, user_id: int) -> Optional[dict]:
        cur = self.conn.cursor()
        cur.execute(
            "SELECT age, gender, looking_for, about, profile_complete FROM users WHERE user_id=%s;",
            (user_id,),
        )
        row = cur.fetchone()
        if not row:
            return None
        return {
            "age": row["age"],
            "gender": row["gender"],
            "looking_for": row["looking_for"],
            "about": row["about"],
            "profile_complete": bool(row["profile_complete"]),
        }

    def set_user_video(self, user_id: int, file_id: str) -> None:
        self.ensure_user(user_id)
        cur = self.conn.cursor()
        # Keep one current video per owner.
        cur.execute("DELETE FROM videos WHERE owner_user_id=%s;", (user_id,))
        cur.execute(
            "INSERT INTO videos(owner_user_id, file_id) VALUES (%s, %s);",
            (user_id, file_id),
        )
        cur.execute("UPDATE users SET has_video=TRUE WHERE user_id=%s;", (user_id,))
        self.conn.commit()

    def clear_user_video(self, owner_user_id: int) -> None:
        self.ensure_user(owner_user_id)
        cur = self.conn.cursor()
        cur.execute("DELETE FROM videos WHERE owner_user_id=%s;", (owner_user_id,))
        cur.execute("UPDATE users SET has_video=FALSE WHERE user_id=%s;", (owner_user_id,))
        self.conn.commit()

    def hide_user_videos(self, owner_user_id: int) -> None:
        self.ensure_user(owner_user_id)
        cur = self.conn.cursor()
        cur.execute("DELETE FROM videos WHERE owner_user_id=%s;", (owner_user_id,))
        cur.execute(
            "UPDATE users SET has_video=FALSE, video_hidden=TRUE WHERE user_id=%s;",
            (owner_user_id,),
        )
        self.conn.commit()

    def delete_video_by_id(self, video_id: int) -> Optional[int]:
        cur = self.conn.cursor()
        cur.execute("SELECT owner_user_id FROM videos WHERE id=%s;", (video_id,))
        row = cur.fetchone()
        if not row:
            return None
        owner_user_id = int(row["owner_user_id"])
        cur.execute("DELETE FROM videos WHERE id=%s;", (video_id,))
        # If owner has no other video rows (shouldn't), clear has_video.
        cur.execute("SELECT 1 FROM videos WHERE owner_user_id=%s LIMIT 1;", (owner_user_id,))
        still_has = cur.fetchone() is not None
        cur.execute("UPDATE users SET has_video=%s WHERE user_id=%s;", (still_has, owner_user_id))
        self.conn.commit()
        return owner_user_id

    def get_user_video(self, owner_user_id: int) -> Optional[Video]:
        self.ensure_user(owner_user_id)
        cur = self.conn.cursor()
        cur.execute(
            "SELECT id, owner_user_id, file_id FROM videos WHERE owner_user_id=%s;",
            (owner_user_id,),
        )
        row = cur.fetchone()
        if not row:
            return None
        return Video(id=row["id"], owner_user_id=row["owner_user_id"], file_id=row["file_id"])

    def pick_next_video(self, viewer_user_id: int) -> Optional[Video]:
        cur = self.conn.cursor()

        # First show videos the user has never seen.
        cur.execute(
            """
            SELECT v.id, v.owner_user_id, v.file_id
            FROM videos v
            JOIN users u ON u.user_id = v.owner_user_id
            WHERE v.owner_user_id != %s
              AND u.video_hidden = FALSE
              AND NOT EXISTS (
                SELECT 1
                FROM views vw
                WHERE vw.viewer_user_id = %s
                  AND vw.video_id = v.id
              )
            ORDER BY RANDOM()
            LIMIT 1;
            """,
            (viewer_user_id, viewer_user_id),
        )
        row = cur.fetchone()
        if row:
            return Video(id=row["id"], owner_user_id=row["owner_user_id"], file_id=row["file_id"])

        # If everyone has already been seen, start showing them again.
        # Do not repeat anyone from the last 5 viewed profiles when possible.
        cur.execute(
            """
            SELECT v.id, v.owner_user_id, v.file_id
            FROM videos v
            JOIN users u ON u.user_id = v.owner_user_id
            WHERE v.owner_user_id != %s
              AND u.video_hidden = FALSE
              AND NOT EXISTS (
                SELECT 1
                FROM (
                  SELECT v2.owner_user_id
                  FROM views vw2
                  JOIN videos v2 ON v2.id = vw2.video_id
                  WHERE vw2.viewer_user_id = %s
                  ORDER BY vw2.viewed_at DESC
                  LIMIT 5
                ) recent
                WHERE recent.owner_user_id = v.owner_user_id
              )
            ORDER BY (
                SELECT vw3.viewed_at
                FROM views vw3
                WHERE vw3.viewer_user_id = %s
                  AND vw3.video_id = v.id
            ) ASC
            LIMIT 1;
            """,
            (viewer_user_id, viewer_user_id, viewer_user_id),
        )
        row = cur.fetchone()

        # With fewer than 6 available profiles, a strict 5-profile cooldown
        # can leave no candidate. In that case, use the oldest viewed profile.
        if not row:
            cur.execute(
                """
                SELECT v.id, v.owner_user_id, v.file_id
                FROM videos v
                JOIN users u ON u.user_id = v.owner_user_id
                JOIN views vw ON vw.video_id = v.id AND vw.viewer_user_id = %s
                WHERE v.owner_user_id != %s
                  AND u.video_hidden = FALSE
                ORDER BY vw.viewed_at ASC
                LIMIT 1;
                """,
                (viewer_user_id, viewer_user_id),
            )
            row = cur.fetchone()

        if not row:
            return None
        return Video(id=row["id"], owner_user_id=row["owner_user_id"], file_id=row["file_id"])

    def mark_viewed(self, viewer_user_id: int, video_id: int) -> None:
        cur = self.conn.cursor()
        cur.execute(
            """
            INSERT INTO views(viewer_user_id, video_id, viewed_at)
            VALUES (%s, %s, CURRENT_TIMESTAMP)
            ON CONFLICT(viewer_user_id, video_id) DO UPDATE SET
              viewed_at=CURRENT_TIMESTAMP;
            """,
            (viewer_user_id, video_id),
        )
        self.conn.commit()

    def add_complaint(self, reporter_user_id: int, video_id: int) -> None:
        self.ensure_user(reporter_user_id)
        cur = self.conn.cursor()
        cur.execute(
            "INSERT INTO complaints(reporter_user_id, video_id) VALUES (%s, %s);",
            (reporter_user_id, video_id),
        )
        self.conn.commit()

    def rate(self, rater_user_id: int, video_id: int, value: int) -> None:
        if value not in (1, -1):
            raise ValueError("rating value must be 1 or -1")
        self.ensure_user(rater_user_id)
        cur = self.conn.cursor()
        cur.execute(
            """
            INSERT INTO ratings(rater_user_id, video_id, value)
            VALUES (%s, %s, %s)
            ON CONFLICT(rater_user_id, video_id) DO UPDATE SET
              value=excluded.value,
              created_at=CURRENT_TIMESTAMP;
            """,
            (rater_user_id, video_id, value),
        )
        self.conn.commit()

    def get_video_likes(self, video_id: int) -> int:
        cur = self.conn.cursor()
        cur.execute(
            "SELECT COUNT(*) AS c FROM ratings WHERE video_id=%s AND value=1;",
            (video_id,),
        )
        row = cur.fetchone()
        return int(row["c"] if row else 0)

    def get_video_dislikes(self, video_id: int) -> int:
        cur = self.conn.cursor()
        cur.execute(
            "SELECT COUNT(*) AS c FROM ratings WHERE video_id=%s AND value=-1;",
            (video_id,),
        )
        row = cur.fetchone()
        return int(row["c"] if row else 0)

    def get_video_views(self, video_id: int) -> int:
        cur = self.conn.cursor()
        cur.execute("SELECT COUNT(*) AS c FROM views WHERE video_id=%s;", (video_id,))
        row = cur.fetchone()
        return int(row["c"] if row else 0)

    def get_video_complaints(self, video_id: int) -> int:
        cur = self.conn.cursor()
        cur.execute("SELECT COUNT(*) AS c FROM complaints WHERE video_id=%s;", (video_id,))
        row = cur.fetchone()
        return int(row["c"] if row else 0)

    def mark_partner_verified(self, user_id: int) -> None:
        self.ensure_user(user_id)
        cur = self.conn.cursor()
        cur.execute(
            """
            INSERT INTO partner_verifications(user_id, verified_at)
            VALUES (%s, CURRENT_TIMESTAMP)
            ON CONFLICT(user_id) DO UPDATE SET verified_at=CURRENT_TIMESTAMP;
            """,
            (user_id,),
        )
        self.conn.commit()

    def is_partner_verified(self, user_id: int) -> bool:
        self.ensure_user(user_id)
        cur = self.conn.cursor()
        cur.execute("SELECT 1 FROM partner_verifications WHERE user_id=%s LIMIT 1;", (user_id,))
        return cur.fetchone() is not None

    def set_partner_check_attempted(self, user_id: int) -> None:
        self.ensure_user(user_id)
        cur = self.conn.cursor()
        cur.execute("UPDATE users SET partner_check_attempted=TRUE WHERE user_id=%s;", (user_id,))
        self.conn.commit()

    def partner_check_attempted(self, user_id: int) -> bool:
        self.ensure_user(user_id)
        cur = self.conn.cursor()
        cur.execute("SELECT partner_check_attempted FROM users WHERE user_id=%s;", (user_id,))
        row = cur.fetchone()
        return bool(row and row["partner_check_attempted"])
